# -*- coding: utf-8 -*-
"""Page View Time Series Visualizer

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F0McH-D56ZWA6fK2YX60dO92GtG22vXD
"""

import os
os.environ ['MPLCONGIGDIR'] = os.getcwd() + "/configs/"
import pandas as pd
import numpy as np
import matplotlib
import seaborn as sns 
import matplotlib.pyplot as plt
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()

df = pd.read_csv("https://raw.githubusercontent.com/kvfasoulakos/Page-View-Time-Series-Visualizer/main/fcc-forum-pageviews.csv", parse_dates=['date'], index_col='date')
df.head()

df.info()

df.describe()

#clean the data
df= df[ 
  (df['value'] >= df['value'].quantile(0.025)) &
  (df['value'] <= df['value'].quantile(0.095))
]

draw_line_plot()

#draw_line_plot
def draw_line_plot():
  fig, ax = plt.subplots(figsize=(15,10))
  ax.plot(df.index, df['value'],'g', linewidth=2)

  ax.set_title('Daily FreecodeCamp Forum page views')
  ax.set_xlabel('Date')
  ax.set_ylabel('Page Views')

  #save image and return fig
  fig.savefig('line_plot.png')
  return fig

draw_bar_plot()

month = df.index.month
year = df.index.year 
df_bar = df.groupby(["year","month"])["value"].mean()
print(df_bar.plot())

def draw_bar_plot():
  #copy and modify data for monthy bar plot
  df["month"] = df.index.month
  df["year"] = df.index.year
  df_bar = df.groupby(["year","month"])["value"].mean()
  #df_bar = df_bar.unstack()

  #draw bar plot
  fig = df_bar.plot.bar(legend = True, figsize=(12,6), ylabel= "Average Page Views", xlabel="Years").figure

  plt.legend(['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'])

  plt.xticks(fontsize =10)
  plt.yticks(fontsize = 10)

  #save image and return fig
  fig.savefig('bar_plot.png')
  return fig

draw_box_plot()

def draw_box_plot():
  #prepare data for box plots
  df_box = df.copy()
  df_box.reset_index(inplace=True)
  df_box['year'] = [d.year for d in df_box.date]
  df_box['month'] = [d.strftime('%b') for d in df_box.date]

  #draw box plots using (seaborn)
  df_box['month_num'] = df_box['date'].dt.month
  df_box = df_box.sort_values('month_num')

  fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(15,5) )
  axes[0] = sns.boxplot(x=df_box['year'], y=df_box['value'], ax=axes[0])
  axes[1] = sns.boxplot(x=df_box['month'], y=df_box['value'], ax=axes[1])

  axes[0].set_title('Year-wise Box Plot (Trend)')
  axes[0].set_xlabel('Years')
  axes[0].set_ylabel('Page Views')

  axes[1].set_title('Month-wise Box Plot (Seasonality)')
  axes[1].set_xlabel('Month')
  axes[1].set_ylabel('Page Views')

  #save image and return fig
  fig.savefig('box_plot.png')
  return fig